export function cardiologist(container){
    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="pressure" class="mt-3"> Oбычное давление</label>`)
    const pressure = document.createElement('input')
    pressure.classList.add('form-control')
    pressure.setAttribute('type', 'text')
    pressure.setAttribute('id', 'pressure')
    pressure.setAttribute('name', 'pressure')
    pressure.setAttribute('placeholder', 'Oбычное давление')
    pressure.setAttribute('required', '')
    container.append(pressure)
    
    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="massIndex">Индекс массы тела</label>`)
    const massIndex = document.createElement('input')
    massIndex.classList.add('form-control')
    massIndex.setAttribute('type', 'number')
    massIndex.setAttribute('id', 'massIndex')
    massIndex.setAttribute('name', 'massIndex')
    massIndex.setAttribute('placeholder', 'Индекс массы тела')
    massIndex.setAttribute('required', '')
    container.append(massIndex)

    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="diseases">Перенесенные заболевания сердечно-сосудистой системы</label>`)
    const diseases = document.createElement('input')
    diseases.classList.add('form-control')
    diseases.setAttribute('type', 'text')
    diseases.setAttribute('id', 'diseases')
    diseases.setAttribute('name', 'diseases')
    diseases.setAttribute('placeholder', 'Перенесенные заболевания')
    diseases.setAttribute('required', '')
    container.append(diseases)

    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="age">Возраст</label>`)
    const age = document.createElement('input')
    age.classList.add('form-control')
    age.setAttribute('type', 'number')
    age.setAttribute('id', 'age')
    age.setAttribute('name', 'age')
    age.setAttribute('placeholder', 'Возраст')
    age.setAttribute('required', '')
    container.append(age)
}

export function dentist(container) {
    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="date">Дата последнего посещения</label>`)
    const date = document.createElement('input')
    date.classList.add('form-control')
    date.setAttribute('type', 'date')
    date.setAttribute('id', 'date')
    date.setAttribute('name', 'date')
    date.setAttribute('required', '')
    container.append(date)
}

export function therapist(container) {
    container.insertAdjacentHTML('beforeend', `<label class='mt-3' for="age">Возраст</label>`)
    const age = document.createElement('input')
    age.classList.add('form-control')
    age.setAttribute('type', 'number')
    age.setAttribute('id', 'age')
    age.setAttribute('name', 'age')
    age.setAttribute('placeholder', 'Возраст')
    age.setAttribute('required', '')
    container.append(age)
}